# Generated by Django 3.2.3 on 2021-07-12 15:24

from django.db import migrations, models
import django.db.models.deletion
import scraper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Botswana', 'Botswana'), ('Burkina_Faso', 'Burkina_Faso'), ('Burundi', 'Burundi'), ('Cote_dIvoire', 'Cote_dIvoire'), ('Ethiopia', 'Ethiopia'), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Kenya', 'Kenya'), ('Namibia', 'Namibia'), ('Niger', 'Niger'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Rwanda', 'Rwanda'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra_Leone', 'Sierra_Leone'), ('South_Africa', 'South_Africa'), ('Tanzania', 'Tanzania'), ('Togo', 'Togo'), ('Uganda', 'Uganda'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=120)),
                ('flag', models.ImageField(default='no_picture.png', upload_to='flags')),
                ('url', models.URLField(blank=True, null=True)),
                ('domain', models.URLField(blank=True, null=True)),
                ('site', models.URLField(blank=True, max_length=500, null=True)),
                ('check_and', models.CharField(blank=True, max_length=500, null=True)),
                ('check_or', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_date', models.DateTimeField(auto_now_add=True)),
                ('CPI_pdf', models.FileField(blank=True, default='cpi.pdf', null=True, upload_to=scraper.models.get_upload_path)),
                ('CPI_doc', models.FileField(blank=True, default='cpi.doc', null=True, upload_to=scraper.models.get_upload_path)),
                ('CPI_excel', models.FileField(blank=True, default='cpi.xlsx', null=True, upload_to=scraper.models.get_upload_path)),
                ('report_excel', models.FileField(blank=True, default='report.xlsx', null=True, upload_to=scraper.models.get_upload_path)),
                ('pdf_Filename', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_Filename', models.CharField(blank=True, max_length=100, null=True)),
                ('excel_Filename', models.CharField(blank=True, max_length=100, null=True)),
                ('report_Filename', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.country')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'ordering': ['-id'],
            },
        ),
    ]
