# Generated by Django 3.2.3 on 2021-07-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(choices=[('Botswana', 'Botswana'), ('Burkina_Faso', 'Burkina_Faso'), ('Burundi', 'Burundi'), ('Cote_dIvoire', 'Cote_dIvoire'), ('Ethiopia', 'Ethiopia'), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Guinee', 'Guinee'), ('Kenya', 'Kenya'), ('Namibia', 'Namibia'), ('Niger', 'Niger'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Rwanda', 'Rwanda'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra_Leone', 'Sierra_Leone'), ('South_Africa', 'South_Africa'), ('Tanzania', 'Tanzania'), ('Togo', 'Togo'), ('Uganda', 'Uganda'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=120),
        ),
    ]
